config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "multi_search#index"
  get "/search" => "multi_search#index", as: 'multi_search'
  get "/search-embed" => "multi_search#search_form_embed", as: 'search_embed'

  # constrained to just the engine(s) we want to show our own single-search
  # results for.
  get "/search/:engine" => "single_search#index", engine: /website|flash|flash-google|reserves/, as: 'single_search'

  # ajax results loader
  BentoSearch::Routes.new(self).draw
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper BentoSearchHelper
end

app/controllers/multi_search_controller.rb
require 'concurrent'

class MultiSearchController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :search_form_embed
  after_action :no_x_frame_options, only: "search_form_embed"

  class_attribute :main_engine_ids
  self.main_engine_ids = %w{catalog articles}
  helper_method :main_engine_ids

  class_attribute :secondary_engine_ids
  ## self.secondary_engine_ids = %w{databases reserves website flash flash-google} # flash = flash (eds)
  self.secondary_engine_ids = %w{databases reserves website flash-google}
  helper_method :secondary_engine_ids

  def self.engine_ids
    main_engine_ids + secondary_engine_ids
  end
  def engine_ids
    main_engine_ids + secondary_engine_ids
  end



  include LinkOutHelper
  helper LinkOutHelper


  def index
    if redirect = redirect_to_search
      redirect_to redirect, status: :found
      return
    end

    # trigger lazy load in controller, just cause
    search_results
  end

  def search_form_embed
    render layout: 'embed'
  end


  protected

  def query
    @query ||= params[:q].try(:strip).presence
  end
  helper_method :query

  def immediate_search_results
    @immediate_search_results ||= begin
      immediate_engine_ids = engine_ids.find_all { |id| BentoSearch.get_engine(id).display_configuration.ajax != :auto   }

      BentoSearch::ConcurrentSearcher.new(*immediate_engine_ids).search(query).results
    end
  end

  def background_search_engines
    @background_search_engines ||= begin
      bg_engines = engine_ids.collect do |id|
        engine = BentoSearch.get_engine(id)
        engine if engine.display_configuration.ajax == :auto
      end.compact

      bg_engines.collect do |engine|
        [engine.engine_id, engine]
      end.to_h
    end
  end


  # Returns a hash key'd by ID. The value will be a hash which always has an engine key/value,
  # and also has a results key/value if target is NOT going to be searched bg-ajax.
  def search_results
    @search_results ||= begin
      if query
        background_search_engines.merge(immediate_search_results)
      else
        {}
      end
    end
  end
  helper_method :search_results

  def bento_search_args_for_object(obj)
    if obj == BentoSearch::Results
      [obj]
    else # it's a BentoSearch::SearchEngine loaded in bg ajax
      [obj, {query: query, load: :ajax_auto}]
    end
  end
  helper_method :bento_search_args_for_object

  def engines
    engine_ids.collect do |engine_id|
      engine = BentoSearch.get_engine(engine_id)
    end
  end

  def search_type_select_options
    [['ALL', nil]].concat(
      engines.collect do |e|
        if e.configuration.for_display.link_out
          [ e.configuration.for_display.heading || e.configuration.id, e.configuration.id ]
        end
      end.compact
    )
  end
  helper_method :search_type_select_options

  def redirect_to_search
    if params[:direct_search].present? && params[:q].present? && engine = BentoSearch.get_engine(params[:direct_search])
      complete_link_out_template( engine.configuration.for_display.link_out, params[:q]  )
    end
  end

  def no_x_frame_options
    response.headers.delete("X-Frame-Options")
  end

end

app/controllers/single_search_controller.rb
class SingleSearchController < ApplicationController
  helper LinkOutHelper

  def index
    results
  end

  protected

  def engine_id
    params[:engine]
  end
  helper_method :engine_id

  def query
    @query ||= params[:q].try(:strip).presence
  end
  helper_method :query

  def engine
    @engine ||= BentoSearch.get_engine(engine_id)
  end
  helper_method :engine

  def results
    unless defined?(@results)
      @results = engine.search(query: query, per_page: 10, page: params[:page]) if query
    end
    @results
  end
  helper_method :results

end

app/helpers/application_helper.rb
module ApplicationHelper
  def radio_button(name:, value:, label:)
    label_tag do
      radio_button_tag(name, value.to_s, params[name].to_s == value.to_s) +
        label
    end
  end
end

app/helpers/link_out_helper.rb
require 'cgi'

module LinkOutHelper

  def complete_link_out_template(template, query)
    if template && template.is_a?(Proc)
      instance_exec &template
    elsif template
      template.gsub("%s", CGI.escape(query))
    end
  end

  def link_to_results(search_args:,
                      url_template: nil,
                      label_template: nil,
                      total_items: nil,
                      **link_to_options)
    return "" unless url_template.present?

    label_template = label_template.presence || "View and filter all %i results"
    compiled_label = label_template.gsub("%i", total_items.to_s)

    link_to_options.reverse_merge!(
      target: "_blank",
      data: {
        label_template: label_template,
        has_results_load_template: true,
      }
    )

    link_to compiled_label, complete_link_out_template(url_template, search_args[:query]), link_to_options
  end
end

app/views/application/_extra_links_header.html.slim
- if search_object.display_configuration.extra_links.present?
    .extra-links-header
      .extra-link-prompt = "Also See Results In"
      ul.extra-links
        - search_object.display_configuration.extra_links.each do |extra_link_conf|
          li.extra-link
            = render partial: 'extra_search_link', locals: { query: query, extra_link_conf: extra_link_conf }

app/views/application/_extra_links_section.html.slim
- if search_object.display_configuration.extra_links.present?
    .additional-resources
      .extra-link-prompt = search_object.display_configuration.extra_links_label || "Additional Resources"
      ul.extra-links
        - search_object.display_configuration.extra_links.each do |extra_link_conf|
          li.extra-link
            = render partial: 'extra_search_link', locals: { query: query, extra_link_conf: extra_link_conf }

app/views/application/_extra_search_link.html.slim
-# pass in locals `query` and `extra_link_conf`
-# A hyperlink or form, depending on extra_link_conf.post == true

- if extra_link_conf.post
  = form_tag(extra_link_conf.action, target: "_blank") do
    - extra_link_conf.hidden_fields.each do |hidden_field_conf|
      = hidden_field_tag hidden_field_conf.first, complete_link_out_template(hidden_field_conf.second, query)
    = submit_tag(extra_link_conf.label, class: "extra-link-submit")
- else
  = link_to extra_link_conf.label, complete_link_out_template(extra_link_conf.link_out, query), target: "_blank"

app/views/application/_result_item.html.erb
<% # copy and paste modification of bento_search _std_item.html.erb
   # to add location/call number and various other customizations
%>

<% #  must pass in locals:
   #    * 'item' that's a BentoSearch::ResultItem
   #    * 'results' that's the BentoSearch::Results (optional, actually)
   #    * 'item_counter', 1-based collection counter, passed in automatically
   #       by rails render collection (little known rails feature),
   #       can be used with results.start to calculate actual result set
   #       index.
   #
   # Custom partials meant to take this place of this one should
   # use same convention, local 'item'.
   #
   # By default we're passing index to item_title partial to display
   # counter for results, not sure if that's going to be generally
   # wanted, but to begin with I'm often taking what I need locally
   # based on user-testing and stuff for my use cases, and making
   # it default.
%>



<% bento_decorate(item) do |item| %>

  <%# for debugging purposes, we'll include the vendor-specific unique_id, if we have
      one, in a data-unique-id attribute. %>

  <div class="bento_item" data-unique-id="<%= item.unique_id %>">
    <% if item.display_format.present? || item.display_language.present? %>
      <div class="bento_item_about">
        <%- if item.display_format.present? -%>
          <span class="bento_format"><%= item.display_format -%></span>
        <%- end -%>
        <%- if item.display_language.present? -%>
          <span class="bento_language"> in <%= item.display_language -%></span>
        <%- end -%>
      </div>
    <% end %>
    <h4 class="bento_item_title">
      <%= link_to_unless(item.link.blank?, item.complete_title, item.link, target: "_blank") %>

      <% if item.display_configuration.try{|h| h[:indicate_fulltext]} && item.link_is_fulltext? %>
        <small class="bento_available_online">Online</small>
      <% end %>
    </h4>

    <div class="bento_item_body">
      <% if item.authors.present? %>
        <div class="bento_item_row first_about">
            <span class="authors">
              <%= item.render_authors_list %>
            </span>
        </div>
      <% end %>

      <% if item.display_configuration.display_source_info != false %>
        <div class="bento_item_row second_about">
          <% if item.display_date.present? %>
            <span class="date"><%=
            if item.display_configuration.year_only
              I18n.localize(item.publication_date, :format => "%Y")
            else
              item.display_date
            end
            %></span>.
          <% end %>

          <% if item.source_title.present? %>
            <span class="source_title"><%= item.source_title %></span>.
          <% elsif item.publisher.present? %>
            <span class="publisher"><%= item.publisher %></span>.
          <% end %>

          <% if text = item.render_citation_details %>
            <%= text %>.
          <% end %>
        </div>
      <% end %>

      <%# some adapters return shelf loc like this... %>
      <% if item.custom_data[:location].present? || item.custom_data[:call_number].present? %>
        <div class="bento_item_row shelf-location">
          <span class="location-label">Location:</span>
          <%= item.custom_data[:location] %>
          <%= item.custom_data[:call_number] %>
        </div>
      <% end %>

      <%# other adapters return shelf loc like this... %>
      <% (item.custom_data[:holdings] || []).each do |holding|  %>
        <div class="bento_item_row shelf-location">
          <span class="location-label">Location:</span>
          <%= holding.location %>
          <%= holding.call_number %>
        </div>
      <% end %>

      <% if item.other_links.present? %>
        <div class="bento_item_other_links">
          <%= render :partial => "bento_search/link", :collection => item.other_links, locals: { :target => "_blank"  } %>
        </div>
      <% end %>
    </div>

    <% if item.abstract %>
      <hr />
      <div class="bento_item_row abstract">
        &ldquo;<%= item.render_summary  %>&rdquo;
      </div>
    <% end %>

  </div>
<% end %>

app/views/bento_search/_link.html.erb
<%= link_to(link.label, link.url,
      :rel    => link.rel,
      :class  => (link.style_classes + ["bento_search_link", "btn", "btn-mini", "btn-default", "btn-sm"]),
      :target => local_assigns[:target] || link.target
      ) %>

<% if link.details %>
  <em class="abstract"><%= link.details %></em>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FordhamLawSearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fordham Law Search</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'embed', media: 'all' %>
    <%= javascript_include_tag 'embed' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/multi_search/_catalog_item.html.erb
<% # copy and paste modification of bento_search _std_item.html.erb
   # to add location/call number
%>

<% #  must pass in locals:
   #    * 'item' that's a BentoSearch::ResultItem
   #    * 'results' that's the BentoSearch::Results (optional, actually)
   #    * 'item_counter', 1-based collection counter, passed in automatically
   #       by rails render collection (little known rails feature),
   #       can be used with results.start to calculate actual result set
   #       index.
   #
   # Custom partials meant to take this place of this one should
   # use same convention, local 'item'.
   #
   # By default we're passing index to item_title partial to display
   # counter for results, not sure if that's going to be generally
   # wanted, but to begin with I'm often taking what I need locally
   # based on user-testing and stuff for my use cases, and making
   # it default.
%>



<% bento_decorate(item) do |item| %>

  <%# for debugging purposes, we'll include the vendor-specific unique_id, if we have
      one, in a data-unique-id attribute. %>

  <div class="bento_item" data-unique-id="<%= item.unique_id %>">
    <%= render :partial => "bento_search/item_title", :object => item, :as => 'item', :locals => {:index => bento_item_counter(local_assigns[:item_counter], local_assigns[:results]) } %>


    <div class="bento_item_body">



      <% if item.any_present?(:authors, :display_date) %>
        <p class="bento_item_row first_about">

          <% if item.authors.present? %>
            <span class="authors">
              <%= item.render_authors_list %>
            </span>
          <% end %>

          <% if item.authors.present? && item.display_date.present? %>
            <span class="seperator"><%= I18n.t("bento_search.author_date_seperator", :default=>"—") %></span>
          <% end %>

          <% if item.display_date.present? %>
            <span class="date">
              <%= item.display_date %>
            </span>
          <% end %>

        </p>
      <% end %>

      <% if item.abstract %>
        <p class="bento_item_row abstract">
          <%= item.render_summary  %>
        </p>
      <% end %>

      <% if item.has_source_info? %>
        <p class="bento_item_row second_about">
          <%= item.render_source_info %>
        </p>
      <% end %>

      <p class="bento_item_row shelf-location">
        Shelf location:
        <%= item.custom_data[:location] %>
        <%= item.custom_data[:call_number] %>
      </p>

      <% if item.other_links.present? %>
        <p class="bento_item_other_links">
          <%= render :partial => "bento_search/link", :collection => item.other_links %>
        </p>
      <% end %>
    </div>

  </div>
<% end %>

app/views/multi_search/_search_form.html.slim
.search-field
  = text_field_tag :q, params[:q]
  '
  = submit_tag :search, name: 'c'
.search-type-options
  - search_type_select_options.each do |text, id|
    = radio_button name: :direct_search, value: id, label: text

app/views/multi_search/_search_results_box.html.slim
-# `search_object` local passed in is either a BentoSearch::Results or a BentoSearch::Engine.
-# if it's just an engine, we load it ajax bg, if it's results we show it.

.div.search-results-box class=search_object.engine_id
  .search-results-box-header
    h2 = search_object.display_configuration.heading || search_object.engine_id
    '
    = link_to_results(search_args: {query: query},
                      url_template: search_object.display_configuration.link_out,
                      label_template: '%i Results →',
                      class: "search-results-count",
                      total_items: number_with_delimiter(search_object.try(:total_items).presence))
    '
  - if search_object.display_configuration.hint
    div.hint = search_object.display_configuration.hint
  hr
  = bento_search *bento_search_args_for_object(search_object)
  - if search_object.display_configuration.link_out.present?
    hr.link-out-separator
    = link_to_results(search_args: {query: query},
                      url_template: search_object.display_configuration.link_out,
                      label_template: search_object.display_configuration.link_out_text,
                      class: "view-all-results-link",
                      total_items: number_with_delimiter(search_object.try(:total_items).presence))
    = render "extra_links_section", search_object: search_object

    - if search_object.display_configuration.show_links_in_header
      script type="text/html" id="#{search_object.engine_id}-header"
        = render "extra_links_header", search_object: search_object

      javascript:
        $(function() {
          $('[data-hook=extra-links-header]').append($('##{search_object.engine_id}-header').html())
        })

app/views/multi_search/index.html.slim
.search-form
  h1 = link_to "https://library.law.fordham.edu" do
    = render partial: 'shared/logo'
    | The Maloney Library
  = link_to "Fordham University School of Law", "https://www.fordham.edu/info/20346/school_of_law", class: "school-name"
  .search-form--content data-hook="extra-links-header"
    = form_tag multi_search_path, method: :get, enforce_utf8: false, class: "search-form--form"
      = render partial: "search_form"

- if search_results.present?
  .search-results
    .search-results-main
      - main_engine_ids.each do |engine_id|
        = render partial: 'search_results_box', locals: { search_object: search_results[engine_id] }
    .search-results-secondary
      - secondary_engine_ids.each do |engine_id|
        = render partial: 'search_results_box', locals: { search_object: search_results[engine_id] }

app/views/multi_search/search_form_embed.html.slim
.search-form
  = form_tag multi_search_url, method: :get, enforce_utf8: false, target: "_blank"
    = render partial: 'search_form'

app/views/multi_search/search_form_embed.js.erb
// Code executed on 'host' page to load the embed iframe.

(function() {

  var getUrlParameter = function(name) {
    name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
    var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
    var results = regex.exec(location.search);
    return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
  };

  var ready = function(fn) {
    if (document.readyState != 'loading'){
      fn();
    } else {
      document.addEventListener('DOMContentLoaded', fn);
    }
  };

  ready(function() {
    var domNodeInsertionPoint;
    var hostDomId = '<%= params["hostDomId"] %>';

    if (hostDomId) {
      domNodeInsertionPoint = document.querySelector("#" + hostDomId);
    }
    if(! hostDomId ) {
      // find the script tag that points to ourselves, with either http or https
      // or protocol-relative.
      domNodeInsertionPoint = document.querySelector("script[src='<%= search_embed_url(format: :js, protocol: false) %>'], script[src='<%= search_embed_url(format: :js, protocol: 'http') %>'], script[src='<%= search_embed_url(format: :js, protocol: 'https') %>']");
    }

    if (! domNodeInsertionPoint) {
      console.log("search_form_embed.js couldn't find a host DOM element to insert at, " + getUrlParameter("hostDomId"));
      return;
    }

    var iFrameUrl = '<%= search_embed_url(format: :html, protocol: false) %>?';
    ['search.focus', 'search.type'].forEach(function(key){
      var value = getUrlParameter(key);
      if(value) {
        iFrameUrl += key + "=" + value + "&";
      }
    });

    var iFrame   = document.createElement("iframe");
    iFrame.src   = iFrameUrl;
    iFrame.style.border = 'none';
    iFrame.style.width = '100%';
    iFrame.style.height = "74px";
    iFrame.scrolling = "no";
    iFrame.className += ' ' + 'fordham-bento-search-form';

    window.addEventListener('message', function(event) {
      if (event.data && event.data.embedFormHeight) {
        iFrame.style.height = event.data.embedFormHeight + "px";
      }
    });

    domNodeInsertionPoint.parentElement.insertBefore(iFrame, domNodeInsertionPoint);
  });

})();

app/views/single_search/index.html.slim
.div.single-search class=engine_id
  .search-form
    = link_to "Fordham University School of Law", "https://www.fordham.edu/info/20346/school_of_law", class: "school-name"
    h1
      = link_to '← Back', root_path(q: query), class: "back-button"
      = engine.configuration.for_display.heading || engine_id
    - if engine.configuration.for_display.hint
      div.hint = engine.configuration.for_display.hint

    = form_tag single_search_path(engine_id), method: :get, enforce_utf8: false
      .search-field
        = text_field_tag :q, query
        '
        = submit_tag :search, name: 'c'


  .single-search-results
    - if results
      - if results.total_items.present? # mostly for reserves which don't have em
        - if (params[:page].to_i > 1) || results.total_items > (results.start + results.per_page)
          .hit-count Page #{params[:page] || '1'} of about #{number_with_delimiter results.total_items} results
        - elsif results.total_items > 0
          .hit-count #{number_with_delimiter results.total_items} results
      = paginate results.pagination
      = bento_search results
      = paginate results.pagination
      = render "extra_links_section", search_object: results